### ISSUE TITLE
As a user I want to be able to select the correct song artist corresponding to the played song sequence, in order to give my guess.

### ISSUE THREAD

**Issue by v4lentin1879** [sopra-fs22-group-17/RaveWave-server#10]
**Development Tasks**

- [x] sopra-fs22-group-17/RaveWave-server#25

- [x] sopra-fs22-group-17/RaveWave-server#26

- [x] sopra-fs22-group-17/RaveWave-client#34
- [x] sopra-fs22-group-17/RaveWave-client#35

- [x] sopra-fs22-group-17/RaveWave-server#64
- [x] sopra-fs22-group-17/RaveWave-server#65
- [x] #97
- [x] #114
- [x] #115
- [x] #126

**Acceptance Criteria:**

- [x] Four artists shall be displayed with one corresponding to the song which is currently played

- [x] The four different artists shall be displayed during the sequence playback

- [x] After the guess has been made the results of the round are displayed

**Priority**: major
