### ISSUE TITLE
As a user I want multiple people being able to play the game at the same time and I want each state of the game to appear concurrently on each users screen in order to ensure a fair game.

### ISSUE THREAD

**Issue by v4lentin1879** [sopra-fs22-group-17/RaveWave-server#11]
**Development Tasks**

- [x] sopra-fs22-group-17/RaveWave-server#19

 
- [x] sopra-fs22-group-17/RaveWave-client#26

- [x] sopra-fs22-group-17/RaveWave-server#22

- [x] sopra-fs22-group-17/RaveWave-server#23

- [x] sopra-fs22-group-17/RaveWave-client#33
- [x] sopra-fs22-group-17/RaveWave-server#45
- [x] sopra-fs22-group-17/RaveWave-server#60
- [x] sopra-fs22-group-17/RaveWave-server#61

- [x] sopra-fs22-group-17/RaveWave-client#19
- [x] sopra-fs22-group-17/RaveWave-server#66
- [x] #76
- [x] #86
- [x] #88
- [x] #105
- [x] #118

**Acceptance Criteria:**

- [x] The game shall start at the same time for each player

- [x] Each game turn should start and end at the same time for every player

- [x] The buttons shall be able to assess the time it took each player to answer

**Priority**: critical
