### ISSUE TITLE
As a developer I want to have a bug free code in order to enable the users to have fun

### ISSUE THREAD

**Issue by v4lentin1879** [sopra-fs22-group-17/RaveWave-server#120]
- [ ] sopra-fs22-group-17/RaveWave-client#149
- [x] sopra-fs22-group-17/RaveWave-server#122
- [ ] sopra-fs22-group-17/RaveWave-client#150
- [ ] sopra-fs22-group-17/RaveWave-client#141
