### ISSUE TITLE
As a user I want to be able to modify the parameters of the selected game, in order to adjust the difficulty and experience of the game

### ISSUE THREAD

**Issue by v4lentin1879** [sopra-fs22-group-17/RaveWave-server#3]
- [x] sopra-fs22-group-17/RaveWave-client#44
- [x] sopra-fs22-group-17/RaveWave-server#74
- [x] sopra-fs22-group-17/RaveWave-server#73
- [x] sopra-fs22-group-17/RaveWave-client#40

**Acceptance Criteria:**

- [x] A user has the ability to change
-  Genre/Mood/Personal Playlist 

- Playback duration/length
- [x]  After modification of these parameters, the user can confirm/abort his selection before starting the game, by clicking on corresponding buttons.

**Priority**: minor
