### ISSUE TITLE
As a user I want to be able to play a sequence of a song (from the Spotify library), in order to answer the upcoming challenges of the selected game mode.

### ISSUE THREAD

**Issue by v4lentin1879** [sopra-fs22-group-17/RaveWave-server#5]
**Development Tasks**

- [x] #47

- [x] sopra-fs22-group-17/RaveWave-server#29

- [x] sopra-fs22-group-17/RaveWave-server#30

- [x] sopra-fs22-group-17/RaveWave-client#3

- [x] sopra-fs22-group-17/RaveWave-client#4
- [x] #49

**Acceptance Criteria:**

- [ ] The song player shall have a button to start/pause playback and to start playback from beginning of the sequence

- [ ] The song player shall only be controllable by the moderator

- [ ] The song player shall display the remaining time of the song sequence playback

- [ ] The song player shall play the song on the default audio output device of the moderator

**Priority**: critical
